#include<iostream>
#include<iomanip>
using namespace std;

int main()
{
   cout << "1" << setw(3);  // Using setw function
   cout << "2" << setw(3);
   cout << "3" << setw(3);
   cout << "4" << endl;
   cout << "2" << setw(3);
   cout << "4" << setw(3);
   cout << "6" << setw(3);
   cout << "8" << endl;
   cout << "3" << setw(3);
   cout << "6" << setw(3);
   cout << "9" << setw(3);
   cout << "12" << endl;
   cout << "4" << setw(3);
   cout << "8" << setw(3);
   cout << "12" << setw(3);
   cout << "16" << endl;
   cout << "22CS050_BINDIYA PATEL" << endl;
   return 0;
}